//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mensaje()
        {
            this.Reciben = new HashSet<Usuario>();
        }
    
        public int Codigo { get; set; }           
                 
        public string TextoMensaje { get; set; }
        
        public string Asunto { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string UsuarioLogueo { get; set; }
        public System.DateTime FechaCaducidad { get; set; }
        public string TipoMensaje { get; set; }
    
        public virtual TipodeMensaje TipodeMensaje { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual HashSet<Usuario> Reciben { get; set; }
    }
}
